version: "3"
services:
  superalgos:
    build: 
      context: ..
      dockerfile: ./Docker/Dockerfile
    image: ghcr.io/martin-b78/superalgos:develop
    command: ["minMemo"]
    ports:
      - '34248:34248'
      - '18041:18041'
    volumes:
      - volume1/docker/Superalgos/mARTin-B78-Superalgos/Data-Storage:/app/Data-Storage
      - volume1/docker/Superalgos/mARTin-B78-Superalgos/Log-Files:/app/Log-Files
      - volume1/docker/Superalgos/mARTin-B78-Superalgos/My-Workspaces:/app/My-Workspaces
    environment:
      PUID: '1000'
      PGID: '1000'
    restart: on-failure
